name = "gamenet"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "GAMENET_KV"
id = "726255c1b3144426b1c6c5cc8a4ff9ff"

[vars]
# Do NOT put ADMIN_PASSWORD here — set it as a secret:
# wrangler secret put ADMIN_PASSWORD
